### PR TITLE
Added Chinese voices

### PR DESCRIPTION
**Pull request by zyren**
A complete Chinese voice files has been produced and tested

### CODE REVIEW

**Comment by edernucci** [comment]
This is amazing @zyren. I'll proceed with checks and merge asap. Thanks for your contribution.

**Comment by richardclli** [comment]
@zyren We do not to have manufacturer specific messages in the sound pack, please remove the RadioMaster specific sound, thanks.

**Comment by zyren** [comment]
> @zyren我们不想在声音包中包含制造商特定的消息，请删除 RadioMaster 特定的声音，谢谢。

Thanks for reminding me ，that Hello.wav has been resubmitted, please review

**Comment by zyren** [comment]
> @zyren我们不想在声音包中包含制造商特定的消息，请删除 RadioMaster 特定的声音，谢谢。

抱歉是我搞错了文件，两个文件名被我搞混了，大意了，还望见谅！

**Comment by richardclli** [comment]
Thanks for updating the hello.wav
For the zh-CN.cav, please change the directory name that matches the directory of the voice files, thanks.  en->cn

**Comment by zyren** [comment]
> Thanks for updating the hello.wav
> For the zh-CN.csv, please change the directory name that matches the directory of the voice files, thanks. en->cn
> zh-CN.csv的文件夾跟voice的不符，請改一下。

感谢提醒，已经修改为cn

**Comment by richardclli** [comment]
I think the Chinese sounds is fine now, @edernucci please consider merging it, thanks.

**Comment by pfeerick** [comment]
@edernucci What's happening with this PR? Any ETA?

**Pull request merged**
