### PR TITLE
feat: Add Chinese Taiwan Voices (Taiwanese,zh-TW) 

### PR DESCRIPTION
**Pull request by zyren**
According to the discussion on https://github.com/EdgeTX/edgetx/pull/2612, add Chinese traditional voices (Chinese Taiwan, zh-TW).

### CODE REVIEW

**Comment by zyren** [comment]
@pfeerick Add zh-TW, please check.

**Comment by HThuren** [comment]
@zyren I think you also want to update /generate.sh

**Comment by zyren** [comment]
> @zyren I think you also want to update /generate.sh

Yes, it has been updated.

**Review by pfeerick — APPROVED** [review]
Looks good. Thanks for adding this :)

**Pull request merged**
