### PR TITLE
PT sound revision

### PR DESCRIPTION
**Pull request by zandorsp**
Remake of PT sounds keeping original system sounds.

Continuation of  #74

### CODE REVIEW

**Review by pfeerick — APPROVED** [review]
I re-added DBM and kilometers from your other PR, and generated the audio. If that looks/sounds ok to you, I'll merge. Note that the files get normalised and trimmed on the release build, so they should get louder if they are quiet now.

**Comment by pfeerick** [comment]
Did you want to add the approriate translations for these since this has just been added?

```
"456","Reverse Thrust","Reverse Thrust","plane","","revthr.wav"
"457","Reverse Thrust On","Reverse Thrust On","plane","","revon.wav"
"458","Reverse Thrust Off","Reverse Thrust Off","plane","","revoff.wav"
"459","Reverse Thrust Idle","Reverse Thrust Idle","plane","","revid.wav"
"460","Forward Thrust","Forward Thrust","plane","","revfwd.wav"
```

**Comment by zandorsp** [comment]
Well, now looks ok. Ready to merge.

**Comment by zandorsp** [comment]
Well, now looks ok. Ready to merge.

**Comment by pfeerick** [comment]
Fantastic, thanks for that! :)

**Pull request merged**
