### PR TITLE
fix: Move `DK` to `DA`, translation updates

### PR DESCRIPTION
**Pull request by HThuren**
To do the change of dk subcatalog to da

### CODE REVIEW

**Comment by pfeerick** [comment]
Can you check why your editor keeps putting double-quotes where it shouldn't - i.e. it seems to keep replacing `"` with `""` in some places, making the CSV files invalid.

**Comment by HThuren** [comment]
I really don't know from where the double qoutes arrive, I use MS Visual Code Studio and Ultraedit, both normally to handle strange formatting etc without change.
But this PR replace #54 (sry, I experience that I are not that good to handle git branches), I close 54.

I fix the 2 .csv files ...

**Comment by HThuren** [comment]
@pfeerick ready for now,, thank you for patience

**Review by pfeerick — APPROVED** [review]

**Comment by HThuren** [comment]
@pfeerick, again thx

**Pull request merged**
