### PR TITLE
feat: Add Danish voice

### PR DESCRIPTION
**Pull request by HThuren**
I have translated the 2 voice files, but had no sucess in the actual text to voice with phyton and azure.
I hope you can do the actual creation, the right neural settings is supposed to be proper chosen.

### CODE REVIEW

**Comment by HThuren** [comment]
Hi @pfeerick, do you have a possibility to try to merge this PR and run the generate of danish voices ?

**Comment by pfeerick** [comment]
Yup. At a glance, it looks fine, and it's generally better for me to do the generation anyway since then I foot the bill if it runs over ;)

**Comment by pfeerick** [comment]
Ok, you might need to re-save those CSV files... they need to be UTF-8 formatted/encoded, otherwise the "special symbols" won't come through properly.

**Comment by HThuren** [comment]
Right, i have made a conversion by ultraedit to uft8, but is it right looking ?

**Comment by pfeerick** [comment]
I'm on mobile atm, but from the github  change view it seems right, getting the proper characters now instead of the nasty unknown diamond questionmark character. Next step will be to run the generator script in about an hour and see if it chokes again ;)

**Comment by HThuren** [comment]
Very god, thx

**Comment by HThuren** [comment]
Thank you, great job by you, most ok, but created a new PR #54 for minor changes

**Pull request merged**
