### PR TITLE
Added source text for LUA scripts audio files

### PR DESCRIPTION
**Pull request by microraptor**
This adds source text for phrases for audio files used in the commonly used LUA scripts Betaflight, iNav telemetry and Yaapu telemetry. Too keep things tidy I put them in a separate script CSV file and their output is generated into separate folders. The idea is that LUA script users can use instead of the builtin audio files these ones, which have the same voice and quality as all the other audio. This is especially nice, since some LUA scripts also use system audio files.

The original sound files can be found here:

- https://github.com/betaflight/betaflight-tx-lua-scripts/tree/master/src/SOUNDS/en
- https://github.com/iNavFlight/OpenTX-Telemetry-Widget/tree/master/src/SCRIPTS/TELEMETRY/iNav
- https://github.com/yaapu/FrskyTelemetryScript/tree/master/HORUS/SD/SOUNDS/yaapu0

Maybe even the functionality can be added to the LUA scripts, that they check for the `SOUNDS/<lang>/SCRIPTS/<script>/` folder themselves and prioritize them over their own audio files, so that the user doesn't have to move and overwrite any files.

This PR only adds the source text and generation framework. The WAV files themselves still have to be generated.

Here is the excerpt added to the readme:

#### SCRIPTS

Inside the language folder (only in `en` for now) there is a folder called `SCRIPTS`, which has audio files for commonly used LUA scripts. These audio files are generated with the same voice as the other audio files of their language pack. Each script has their own folder.

##### BETAFLIGHT

Audio files for [Betaflight TX Lua Scripts](https://github.com/betaflight/betaflight-tx-lua-scripts). Copy the WAV files from `SOUNDS/<lang>/SCRIPTS/BETAFLIGHT/` to `SOUNDS/en/` to overwrite the original audio files of the script.

##### INAV

Audio files for [iNav Lua Telemetry Flight Status](https://github.com/iNavFlight/OpenTX-Telemetry-Widget). Copy the WAV files from `SOUNDS/<lang>/SCRIPTS/INAV/` to `SCRIPTS/TELEMETRY/iNav/<lang>/` to overwrite the original audio files of the script.

##### YAAPU

Audio files for [Yaapu Telemetry Script and Widget](https://github.com/yaapu/FrskyTelemetryScript). Copy the WAV files from `SOUNDS/<lang>/SCRIPTS/YAAPU/` to `SOUNDS/yaapu0/<lang>/` to overwrite the original audio files of the script.

### CODE REVIEW

**Comment by microraptor** [comment]
If this makes the release too big, perhaps the YAAPU folder should be released extra, since it has the most audio files and is only relevant for people flying ArduPilot.

**Comment by pfeerick** [comment]
I suspect the size won't be that big, especially for a single language. Otherwise, I would instead want to split these into an extras pack - as they aren't directly related to the ETX firmware and normal set of extra files. I'll see what it looks like after it is generated.

**Comment by pfeerick** [comment]
Looks like this came in at ~12MB... so ~24MB for the existing files + ~12MB... I don't think there will be any real complaints about that since most radios have at least a 256MB minimum SD card supplied 😆

**Comment by microraptor** [comment]
Awesome, thanks for generating all the files :)

**Pull request merged**
