### PR TITLE
Add sounds for reverse thrust

### PR DESCRIPTION
**Pull request by Forceu**
At the moment there are no sounds for reverse thrust, I added them to en-GB and en-US.

Also I tried generating the sounds, however the voice sounds different. What voice is being used for the default EN files? I tried `en-US-MichelleNeural` as stated in the Readme. Also, are non-default pitch and speed settings being used?

### CODE REVIEW

**Comment by pfeerick** [comment]
Please look at https://github.com/EdgeTX/edgetx-sdcard-sounds/blob/main/generate.sh ... the example in the readme is just that... one example.

**Comment by pfeerick** [comment]
I'll need to double-check, but IIRC "user" sounds are limited to 6 character filenames, and "system" sounds can be up to 8 characters. So these will need to be shortened.

**Comment by Forceu** [comment]
Thanks, I renamed the files to have a different prefix and to be 6 characters maximum.

> Please look at https://github.com/EdgeTX/edgetx-sdcard-sounds/blob/main/generate.sh

I had a look at it before, it didn't specify what the default `en` uses, in the end I found out that the voice is `en-IE-EmilyNeural`

**Comment by pfeerick** [comment]
Thanks for that. Hopefully we can get rid of that limit, but for now, it's what we've got to work with. 

Yeah, sometimes can't see the forest for all the trees 😆 
https://github.com/EdgeTX/edgetx-sdcard-sounds/blob/c0d6ce9767afebde33e72d910f9bc3ada653c407/generate.sh#L21

**Pull request merged**
