### PR TITLE
Glider specific SE audio/phrases for SoarETX

### PR DESCRIPTION
**Pull request by ulfhedlund**
Added glider specific SE audio/phrases for SoarETX, plus a few missing sounds for cars.

### CODE REVIEW

**Comment by pfeerick** [comment]
Just FYI, I'll leave this on hold until #100 goes in, so they stay in sync. I'll generate the audio now though.

**Comment by frankiearzu** [comment]
@ulfhedlund 
Did a few changes to the sounds in SoarETX v2, tried to re-use some existing sounds, and only added a few new ones.

Do you mind chaining this ones:

Already Existing (at least in English)
Disarmed     se2drm.wav -> disarm.wav    OLD file
Cruise          se2cru.wav  ->  cruise.wav OLD file
Flaps Up      se2flu.wav   -> flapup.wav OLD file
Flight Mode Lunch   se2lch.wav  -> fm-lch.wav OLD  file
Landing       se2lnd.wav  -> landin.wav OLD file

New ones (not in current files)
Motor Armed   se2arm.wav -> motarm.wav
Power               se2pwr.wav -> power.wav  
Speed              se2spd.wav  -> speed.wav
Thermal           se2thm.wav -> therml.wav

**Comment by pfeerick** [comment]
@ulfhedlund Does this look (sound?) right now?

**Comment by ulfhedlund** [comment]
@pfeerick - I am travelling/on leave and have been unable to make the changes that @frankiearzu asked for.
I suppose I need to fix that before merge, right? I'll try and do that tonight (within the next few hours).

**Comment by ulfhedlund** [comment]
@pfeerick - you seem to have fixed it all - thanks! OK to go!

**Comment by frankiearzu** [comment]
looks good to me too, thanks @pfeerick

**Pull request merged**
