### PR TITLE
Added suggestions for missing phrases and small cleanup

### LINKED ISSUE #26: Add more words/phrases
- SAFE on
- SAFE off
- timer 1 reset
- timer 2 reset
- timer 3 reset
- expo 1
- expo 2
- expo 3

Check for
- Launch Mode
- Loiter
- Return to Launch

### PR DESCRIPTION
**Pull request by microraptor**
I added missing phrases to en-US.csv and en-GB.csv. Almost all of them are modes from Betaflight and iNav. I also added the ones suggested in PR #30  and issue #26 . I tried to be as consistent as possible with the filename abbreviations and made sure no other phrases with the same meaning already exist.

There is the question how to handle compunded phrases. Quite a few phrases can already be compunded with existing sound files like "O S D Profile 2", "V T X 400 milliwatts" and all the modes which are "on", "active" or "off". However, it is more complicated to configuring edgeTX to use multiple sound files for actions and probably also doesn't sound as good as having one dedicated sound file.

Additionally, I did some polishing and formatted the capitalization of words to be consistent throughout the file, as well as added some context in the almost empty context column. All changes are also applied to the en-GB.csv file.

Please note, I changed only en-US.csv and en-GB.csv. The new WAV files for the 5 english packs still have to be generated. 

Resolves #26, resolves #30

### CODE REVIEW

**Comment by pfeerick** [comment]
This looks great! Only catch is max filename for non-SYSTEM filenames is 6 characters :(

**Comment by pfeerick** [comment]
Can you also add 

SAFE on
SAFE off

As these are in reference to the Spektrum SAFE functionality...

**Comment by SumolX** [comment]
Really glad my changes are being incorporated.  I had also looked into sliming down the number of samples at first but did not find a way to make it sound natural.... thus I figured well might as well do all possible combinations while I'm at it.

**Comment by microraptor** [comment]
I agree that making multiple possible combinations for phrases is the way to go. It is easier for a user to search the csv for their phrase with crtl+f, than trying to add single words together in software. And it also sounds better.

**Comment by microraptor** [comment]
> This looks great! Only catch is max filename for non-SYSTEM filenames is 6 characters (minus extension) (or at least I'm pretty sure it is?!)... hopefully in the future this can be extended on the future but we're not there yet... :(

Thanks for the feedback. I updated the PR to only 6 character long filenames. Sorry, I wasn't aware of the "Sensor Assisted Flight Envelope". I also added "flight envelope protection active/off" just because it sounds awesome.

I also found two previous non-system files with a 7 char long name. I shortened them as well in the csv, the wav files and other languages which have them. While I was at it, I noticed that in Czech some files have Czech names, which I guess is not ideal and should probably be in English to make language switching seamless.

**Comment by pfeerick** [comment]
Yes, indeed... I initially was thinking the same (join multiple words/phrases together) but quickly realised it wouldn't be best, so just having both is the most flexible... if we had analytics for use, I bet not many people would bother joining words together... simpler to request it be added. ;)

And nice... thanks for catching the other "too long" filenames... that is one of the things I need to add to the "build-checks" when that happens... there's a place for it in the github action... just doesn't exist yet 😆 

Consistency is good... of the goals I have in mind (which is one reason I added the first column, the ID number) is to be able to eventually either be able to merge all the languages into a single file, or at least be able to look up the same ID in every file if something needs to be changed. However, it's all the variations in the files that were doing my head in, as words/phrases have been added to some, but not all the files over time, and then there are some dialect-specific variations... so it was getting to be a pain trying to sync them all up. But it is slowly getting better and better. 

Anyway, I'll have a proper look at this tomorrow, and run a new audio generation pass on it.

**Comment by microraptor** [comment]
Trying to keep all the languages synced up and tidy sounds like a real nightmare, because the phrases usually don't translate one to one. It is probably best to have English as a lead language and have all the IDs with the same filenames in the other languages, even if the translation text are duplicates of other phrases. And if there is a request to have a phrase, which is unique another language, then add that as well, even if the English text is a duplicate of a previous phrase.

BTW I have another PR coming up later which you can then also put through the generator, if you like the idea :)

**Comment by microraptor** [comment]
I added a few more phrases which I think could be useful. But this should be it now from my part.

**Comment by pfeerick** [comment]
That may not have across quite right... Ideally, all the languages should have exactly the same phrases - especially for system words/phrases. The only variation should be where it seems some language sets have male and female variations. So, in the context of English language set, all that would happen is those IDs would be skipped over until the sets are back in alignment. The hard part is undoing the mess that is "word/phrase X" added to DE, but not any other language. And "word/phrase Y added to EN, FR and PL, but not any other". They are a mess that way.

**Comment by microraptor** [comment]
That does indeed sound like a mess. I was just saying that there will be duplicates in the translations for sure, because as an example turtles and tortoises are described in German mostly with the same word.

**Pull request merged**
