### PR TITLE
Add GB voices and include JSON index

### PR DESCRIPTION
**Pull request by howels**
Including an index so Flasher has an easier time reading a list of available sound packs.

### CODE REVIEW

**Comment by howels** [comment]
@CoderElectronics please let me know if you would like any changes. Thanks.

**Comment by CoderElectronics** [comment]
Looks good to me!

**Comment by CoderElectronics** [comment]
@edernucci Would you mind merging this in? Thank you :)

**Comment by pfeerick** [comment]
@edernucci Zip file release is needed for this also, as it is currently causing Flasher to hang because the zips are missing ;)

**Pull request merged**
