### PR TITLE
feat(zh-CN): Add new words and phrases, add voice to generator script

### PR DESCRIPTION
**Pull request by zyren**
All voice files have been made as listed in the new CSV file.

### CODE REVIEW

**Review by pfeerick — CHANGES_REQUESTED** [review]
Firstly, thank you! :)

The three renamed files have filenames that are too long - non-system files have a limit of 6 character filenames (minus extension). 

```
pfeerick@DESKTOP-RSREF72:~/repos/edgetx-sdcard-sounds$ ./build-checks.sh 
File name length checks...
Filename is too long: SOUNDS/cn/landing.wav
Filename is too long: SOUNDS/cn/pattern.wav
Filename is too long: SOUNDS/cn/takeoff.wav
```

Can you also update the zh-CN entry in https://github.com/EdgeTX/edgetx-sdcard-sounds/blob/main/generate.sh so it can be used in the future for generating sounds ... it's mainly just missing the  voice name

**Comment by zyren** [comment]
> Firstly, thank you! :)
> 
> The three renamed files have filenames that are too long (plus they don't match the names in the csv) - non-system files have a limit of 6 character filenames (minus extension).
> 
> ```
> pfeerick@DESKTOP-RSREF72:~/repos/edgetx-sdcard-sounds$ ./build-checks.sh 
> File name length checks...
> Filename is too long: SOUNDS/cn/landing.wav
> Filename is too long: SOUNDS/cn/pattern.wav
> Filename is too long: SOUNDS/cn/takeoff.wav
> ```
> 
> Can you also update the zh-CN entry in https://github.com/EdgeTX/edgetx-sdcard-sounds/blob/main/generate.sh so it can be used in the future for generating sounds ... it's mainly just missing the voice name

Oh no problem, I'll fix it right away.

**Comment by pfeerick** [comment]
So which of the zn-CN voices are you using to generate that audio? 

i.e. either one of the voices listed against `zh-CN` here https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support?tabs=stt-tts#prebuilt-neural-voices

or can be demoed here https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech/#features

**Comment by zyren** [comment]
> 

Sorry I didn't figure it out before, now I know what to do.

**Review by pfeerick — APPROVED** [review]

**Comment by pfeerick** [comment]
Thank you! :) Just means it's ready to go now if more need to be added, or I need to regenerate from scratch.

**Comment by zyren** [comment]
> Thank you! :) Just means it's ready to go now if more need to be added, or I need to regenerate from scratch.

Yes, the audio files I uploaded were made with other TTS tools, I just found out today that Microsoft's TTS is more natural and sounding better, please regenerate if possible.

**Comment by pfeerick** [comment]
Sure, can do that. :) I'll merge this as is, and regenerate the zh-CN pack tomorrow.

**Pull request merged**
