### PR TITLE
feat: sv-SE (Swedish) generation files added 🇸🇪

### PR DESCRIPTION
**Pull request by ulfhedlund**
Added files for generation of Swedish standard sounds, as well as for INAV. Betaflight and Yaapu sounds are not included.
Voice used is sv-SE-SofieNeural.

### CODE REVIEW

**Comment by pfeerick** [comment]
Would it be possible for you to have the "Source text" in English, i.e. as in the Japanese (ja-JP) or Chinese (zh-CN) translations. The other translation files are still the old format (i.e. really only have the destination translation format), so aren't' the best reference. The idea is that a dual language speaker can see what the original intent was, and then translate as required. And for English speakers like myself to be able to add new phases in English, ready for translation. 

This will eventually be used for Crowdin translation as well, but not there yet.

**Comment by pfeerick** [comment]
I am a little pedantic about the CSV formatting (i.e. quotes) as it 1) helps with lining stuff up in code editor that has color formatting if not using a speadsheet tool to work on the files as more color is shown and 2) ensures multi-word strings don't get mangled somewhere along the way.

image

**Comment by ulfhedlund** [comment]
> 

Absolutely, I thought it was a bit strange to have both source text and translation in Swedish. I'll get that sorted but it will take a while since I will be travelling for a few days.

**Comment by ulfhedlund** [comment]
Was an easy fix so I have now added source text in English and also translations for Betaflight.
Some of the translations are more of a phonetic kind, since the translator has some quirky pronunciations (the letter D for example) and some words are really awkward to translate (angle, horizon and acro mode for example). But all are tested and sounds reasonably OK, I think. 
And sorry, the quoting is all gone.

**Comment by pfeerick** [comment]
Doesn't have to be perfect first time around... at least there is something we can get some ears on ;) Once the radio knows about sv-SE, that is ;) Thanks for this! :)

**Pull request merged**
